### ISSUE TITLE
Random "Project was not passed and could not be determined from the environment"

### ISSUE THREAD

**Issue by fgsalomon** [googleapis/python-storage#1131]
Hi,

I'm using this library inside a REST service made and while most of the time it works perfectly sometimes I get these errors:

```
OSError: Project was not passed and could not be determined from the environment.
```

The service is implemented with FastAPI and runs inside a GKE cluster using default application credentials (as documented [here](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity)).

#### Environment details

  - OS type and version: Debian Bullseye Docker container 
  - Python version: 3.11
  - pip version: 22.3.1
  - `google-cloud-storage` version: 2.10.0
  - FastAPI: 0.103.0
  - GKE: 1.24.14-gke.2700

#### Stack trace
```
    self.storage_client = storage.Client()
                          ^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/google/cloud/storage/client.py", line 173, in __init__
    super(Client, self).__init__(
  File "/root/.local/lib/python3.11/site-packages/google/cloud/client/__init__.py", line 320, in __init__
    _ClientProjectMixin.__init__(self, project=project, credentials=credentials)
  File "/root/.local/lib/python3.11/site-packages/google/cloud/client/__init__.py", line 271, in __init__
    raise EnvironmentError(
OSError: Project was not passed and could not be determined from the environment.
```

What could be the cause of these errors? How can I avoid them?

Thanks!

**Comment by cojenco** [comment]
Hi fgsalomon, could you elaborate more on your workflow, especially where/when/how the storage client is instantiated? Also could you share if your program uses any other libraries that may also interact with google cloud storage? 

What stands out to me is that this error happens sporadically. A couple initial thoughts... Would it be possible to explicitly pass in the project in the client constructor? Or to set environment variable "GOOGLE_CLOUD_PROJECT" to be equal to your project name? See [here](https://github.com/googleapis/python-cloud-core/blob/ec6c69e1a1ea44365959cdb82329c26253d97286/google/cloud/client/__init__.py#L256-L274) how the project is determined upon client instantiation.

**Comment by fgsalomon** [comment]
> here

Hi @cojenco.

Thanks for your reply 😃 

Setting `GOOGLE_CLOUD_PROJECT` as environment variable has worked, no error has happened since using it.

However, I'm still curious about why the error happens randomly without the env var. I believe is load related because the error only happens on the production cluster and not the development cluster.


The code I'm using is very simple and similar to something like this:

```py
from uuid import uuid4

from fastapi import FastAPI, UploadFile, File
from google.cloud import storage

app = FastAPI()


class GCSRepository:

    def __init__(self, bucket_name: str):
        self.storage_client = storage.Client()
        self.bucket_name = bucket_name

    def save(self, name: str, content: bytes, content_type: str|None) -> None:
        bucket = self.storage_client.get_bucket(self.bucket_name)
        gc_blob = bucket.blob(name)
        gc_blob.upload_from_string(
            content,
            content_type=content_type if content_type else "text/plain",
            num_retries=3,
            timeout=10,
        )


@app.get("/")
async def upload_file(file: UploadFile = File(description="File to be uploaded to GCS")):
    file_content = await file.read()
    repository = GCSRepository(bucket_name="my-bucket")
    uploaded_filename = f"upload-{str(uuid4())}"
    repository.save(name=uploaded_filename, content=file_content, content_type=file.content_type)
    return {"message": f"File uploaded as {uploaded_filename}"}
```

The full list of dependencies is:

```
iohttp==3.8.5
aiosignal==1.3.1
annotated-types==0.5.0
anyio==4.0.0
async-timeout==4.0.3
attrs==23.1.0
cachetools==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.7
cryptography==41.0.4
dataclasses-json==0.5.6
deprecation==2.1.0
ecs-logging==2.1.0
elastic-apm==6.18.0
elasticsearch==7.17.9
fakeredis==2.19.0
fastapi==0.103.0
filetype==1.2.0
frozenlist==1.4.0
google-api-core==2.12.0
google-auth==2.23.0
google-cloud-core==2.3.3
google-cloud-storage==2.10.0
google-crc32c==1.5.0
google-resumable-media==2.6.0
googleapis-common-protos==1.60.0
greenlet==2.0.2
gunicorn==20.1.0
h11==0.14.0
httpcore==0.18.0
httptools==0.6.0
httpx==0.25.0
idna==3.4
iso3166==2.1.1
json-logging-py==0.2
loguru==0.7.2
marshmallow==3.20.1
marshmallow-enum==1.5.1
meiga==1.9.2
multidict==6.0.4
mypy-extensions==1.0.0
packaging==23.1
petisco==2.0.0rc28
pika==1.3.2
prometheus-client==0.17.1
prometheus-fastapi-instrumentator==6.0.0
protobuf==4.24.3
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
pydantic==2.4.1
pydantic-settings==2.0.3
pydantic_core==2.10.1
PyJWT==2.4.0
PyMySQL==1.0.3
python-dateutil==2.8.1
python-dotenv==1.0.0
python-multipart==0.0.6
PyYAML==6.0.1
redis==4.6.0
requests==2.31.0
requests-toolbelt==0.10.1
rsa==4.9
six==1.16.0
slack-sdk==3.21.3
sniffio==1.3.0
sortedcontainers==2.4.0
SQLAlchemy==2.0.21
SQLAlchemy-Utils==0.41.1
starlette==0.27.0
StrEnum==0.4.9
stripe==6.4.0
typing-inspect==0.9.0
typing_extensions==4.8.0
urllib3==1.26.16
uvicorn==0.23.2
uvloop==0.17.0
validators==0.22.0
watchfiles==0.20.0
websockets==11.0.3
wrapt==1.15.0
yarl==1.9.2
```

**Comment by cojenco** [comment]
Closing issue out, as the error is no longer happening. If not, please feel free to reopen, thanks!

**Comment by abhijit156** [comment]
Hi @cojenco, I followed the steps outlined here but still running into the same error.
I am on a Windows system, and facing this issue when I try to run a `docker run` command
**Environment details** 
System OS and Version -
```
WindowsVersion WindowsBuildLabEx
-------------- -----------------
2009           19041.1.amd64fre.vb_release.191206-1406  
```
Docker Container OS Type and Version - python:3.11-alpine
PYTHON_VERSION = 3.11.9
PYTHON_PIP_VERSION = 24.0
PYTHON_SETUPTOOLS_VERSION = 65.5.1
google-cloud-storage version =2.16.0
FastAPI version = 0.111.0
gunicorn version = 22.0.0

Here are some checks I made - 
`gcloud config get-value project` returns the expected project name.
The `default_application_credentials.json` file is in the right path, is being read in correctly, and also contains the project name as expected.
`echo $env:GOOGLE_CLOUD_PROJECT` also returns the project name as expected.
`gcloud auth list` returns the expected credentialed account. 

**Stack Trace**
```
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 67, in run    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]", prog=prog).run()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 236, in run  
    super().run()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 72, in run   
    Arbiter(self).run()
    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 118, in setup 
    self.app.wsgi()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi  
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module     
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/main.py", line 45, in <module>
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
122, in __init__
    super(Client, self).__init__(
  File "/usr/local/lib/python3.11/site-packages/google/cloud/client/__init__.py", line 320, in __init__
    _ClientProjectMixin.__init__(self, project=project, credentials=credentials)
  File "/usr/local/lib/python3.11/site-packages/google/cloud/client/__init__.py", line 271, in __init__
    raise EnvironmentError(
OSError: Project was not passed and could not be determined from the environment.  

```
