### ISSUE TITLE
DefaultCredentialsError at /admin/users/team/add/  File 8844656af62eeebcb855178a8f5ceac8fa5bdb93 was not found.

### ISSUE THREAD

**Issue by reyesvicente** [googleapis/python-storage#119]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-storage/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: Mac OS Catalina 10.15.4
  - Python version: `python --version`: 3.8.0
  - pip version: `pip --version`: pip 20.0.2 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)
  - `google-cloud-storage` version: `pip show google-cloud-storage`: I use django-storages[google]==1.9.1

#### Steps to reproduce

  1. I login on the admin
  2. Upload a photo on a Team Member
  3. The next screen shows `DefaultCredentialsError at /admin/users/team/add/  File 8844656af62eeebcb855178a8f5ceac8fa5bdb93 was not found.`
  4. Keys are at 

`.envs/.production/.django`
```
GOOGLE_APPLICATION_CREDENTIALS='/home/djangoadmin/covid_virus_tracker/cvt/config/<file_name>.json'
DJANGO_GCP_STORAGE_BUCKET_NAME=covid_virus_tracker
```
#### Code example
`production.py` # cookiecutter-django
```python
from .base import *  # noqa
from .base import env

GS_BUCKET_NAME = env("DJANGO_GCP_STORAGE_BUCKET_NAME")
GS_DEFAULT_ACL = "publicRead"
DEFAULT_FILE_STORAGE = "covid_virus_tracker.utils.storages.MediaRootGoogleCloudStorage"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
```
`base.py`
```python
import environ
env = environ.Env()
```

#### Stack trace
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1638, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1565, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1081, in save_model
    obj.save()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 745, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 782, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 887, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 924, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1390, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1333, in as_sql
    value_rows = [
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1334, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1334, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1285, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/files.py", line 288, in pre_save
    file.save(file.name, file.file, save=False)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/files.py", line 87, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/usr/local/lib/python3.8/site-packages/django/core/files/storage.py", line 51, in save
    name = self.get_available_name(name, max_length=max_length)
  File "/usr/local/lib/python3.8/site-packages/storages/backends/gcloud.py", line 297, in get_available_name
    return super(GoogleCloudStorage, self).get_available_name(name, max_length)
  File "/usr/local/lib/python3.8/site-packages/django/core/files/storage.py", line 82, in get_available_name
    while self.exists(name) or (max_length and len(name) > max_length):
  File "/usr/local/lib/python3.8/site-packages/storages/backends/gcloud.py", line 209, in exists
    return bool(self.bucket.get_blob(self._encode_name(name)))
  File "/usr/local/lib/python3.8/site-packages/storages/backends/gcloud.py", line 141, in bucket
    self._bucket = self._get_or_create_bucket(self.bucket_name)
  File "/usr/local/lib/python3.8/site-packages/storages/backends/gcloud.py", line 149, in _get_or_create_bucket
    bucket = self.client.bucket(name)
  File "/usr/local/lib/python3.8/site-packages/storages/backends/gcloud.py", line 132, in client
    self._client = Client(
  File "/usr/local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 109, in __init__
    super(Client, self).__init__(
  File "/usr/local/lib/python3.8/site-packages/google/cloud/client.py", line 227, in __init__
    Client.__init__(self, credentials=credentials, _http=_http)
  File "/usr/local/lib/python3.8/site-packages/google/cloud/client.py", line 132, in __init__
    credentials, _ = google.auth.default()
  File "/usr/local/lib/python3.8/site-packages/google/auth/_default.py", line 308, in default
    credentials, project_id = checker()
  File "/usr/local/lib/python3.8/site-packages/google/auth/_default.py", line 165, in _get_explicit_environ_credentials
    credentials, project_id = _load_credentials_from_file(
  File "/usr/local/lib/python3.8/site-packages/google/auth/_default.py", line 91, in _load_credentials_from_file
    raise exceptions.DefaultCredentialsError(

Exception Type: DefaultCredentialsError at /cvt-admin/users/team/add/
Exception Value: File 8844656af62eeebcb855178a8f5ceac8fa5bdb93 was not found.
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by frankyn** [comment]
Hi @reyesvicente,

Thanks for filing the issue. Have you tried passing in credentials using example provided in django documentation:

```python
from google.oauth2 import service_account

GS_CREDENTIALS = service_account.Credentials.from_service_account_file(
    "path/to/credentials.json"
)
```

I'm also curious if the file exists, but assuming that it does for now. Do know which version of google-cloud-storage is being used? `pip freeze` can help here.

**Comment by reyesvicente** [comment]
> Hi @reyesvicente,
> 
> Thanks for filing the issue. Have you tried passing in credentials using example provided in django documentation:
> 
> ```python
> from google.oauth2 import service_account
> 
> GS_CREDENTIALS = service_account.Credentials.from_service_account_file(
>     "path/to/credentials.json"
> )
> ```
> 
> I'm also curious if the file exists, but assuming that it does for now. Do know which version of google-cloud-storage is being used? `pip freeze` can help here.

The json file is present and is at `config/credentials.json`

On the `config/settings/production.py`, these are the settings for my storage: 

```
# STORAGES
# ------------------------------------------------------------------------------
# https://django-storages.readthedocs.io/en/latest/#installation
INSTALLED_APPS += ["storages"]  # noqa F405
GS_BUCKET_NAME = env("DJANGO_GCP_STORAGE_BUCKET_NAME")
GS_DEFAULT_ACL = "publicRead"
# STATIC
# ------------------------
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
# MEDIA
# ------------------------------------------------------------------------------
DEFAULT_FILE_STORAGE = "covid_virus_tracker.utils.storages.MediaRootGoogleCloudStorage"
MEDIA_URL = f"https://storage.googleapis.com/{GS_BUCKET_NAME}/media/"
```

**Comment by frankyn** [comment]
I don't see:
```
GS_CREDENTIALS = service_account.Credentials.from_service_account_file(
    "path/to/credentials.json"
)
```
Have you tried adding this to your configuration? I think this is starting to get into a django-storages issue in this case. Recommend filing an issue here: https://github.com/jschneier/django-storages/issues in case adding this doesn't help.

**Comment by reyesvicente** [comment]
> Hi @reyesvicente,
> 
> I don't see something similar to:
> 
> ```
> GS_CREDENTIALS = service_account.Credentials.from_service_account_file(
>     "path/to/credentials.json"
> )
> ```
> 
> Have you tried adding this to your configuration? Also the path to credentials.json should be absolute, so the full path starting from root directory should be provided.
> 
> I think this is starting to get into a django-storages issue in this case. Recommend filing an issue here: https://github.com/jschneier/django-storages/issues in case adding this doesn't help.

The `"path/to/credentials.json"` is on my `.envs/.production/.django` in cookiecutter-django. 

`.envs/.production/.django`
```
GOOGLE_APPLICATION_CREDENTIALS='../config/credentials.json'
```

**Comment by frankyn** [comment]
Oh, instead of using relative path `../config/credentials.json`, could you use an absolute path: `/from/root/config/credentials.json` in your `.envs/.production/.django` file?

**Comment by frankyn** [comment]
Hi @reyesvicente did you have any luck since my last comment? If you're unblocked can we close out this issue?
