### ISSUE TITLE
Need to be able to download objects without storage.bucket.get permission same as gsutil

### ISSUE THREAD

**Issue by marwansalem** [googleapis/python-storage#1225]
When using the python library

```python
from google.cloud import storage
storage_client = storage.Client(os.environ["PROJECT_ID"])

bucket = storage_client.get_bucket(bucket_name)

my_blob = bucket.blob(path_on_bucket)
my_blob.download_to_filename(download_path)
```
The step where I fetch the bucket fails due to required permission (`storage.bucket.get`

```
bucket = storage_client.get_bucket(bucket_name)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/usr/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 782, in get_bucket
    bucket.reload(
  File "/home/usr/.local/lib/python3.8/site-packages/google/cloud/storage/bucket.py", line 1082, in reload
    super(Bucket, self).reload(
  File "/home/usr/.local/lib/python3.8/site-packages/google/cloud/storage/_helpers.py", line 246, in reload
    api_response = client._get_resource(
  File "/home/usr/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 387, in _get_resource
    return self._connection.api_request(
  File "/home/usr/.local/lib/python3.8/site-packages/google/cloud/storage/_http.py", line 72, in api_request
    return call()
  File "/home/usr/.local/lib/python3.8/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
  File "/home/usr/.local/lib/python3.8/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/usr/.local/lib/python3.8/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/usr/.local/lib/python3.8/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
  File "/home/usr/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.Forbidden: 403 GET https://storage.googleapis.com/storage/v1/b/bucket_name?projection=noAcl&prettyPrint=false: my-svc-account@my-project.iam.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket. Permission 'storage.buckets.get' denied on resource (or it may not exist).
```

However while using gsutil, I can download a file without this permissio,  I just pass the GCS URI:
```bash
gsutil cp $path_on_bucket $download_path
```

If there is a way to download objects without having to deal with the bucket using this library, that would be great

**Comment by marwansalem** [comment]
I was  to get a bucket object using this `bucket = storage_client.bucket(bucket_name)`
this does not require storage.buckets.get
