### ISSUE TITLE
blob.upload_from_file() fails with "o.UnsupportedOperation: seek" when given a tarfile fileobj

### ISSUE THREAD

**Issue by jmdobry** [googleapis/python-storage#345]
#### Environment details

Python app deployed to Cloud Run following Cloud Run's Quickstart documentation.

#### Steps to reproduce

1. Acquire a `fileobj` by extracting a file from tarfile (see example code)
1. Attempt to upload that `fileobj` to GCS using `blob.upload_from_file`

#### Code example

```python
from google.cloud import storage
import requests

storage_client = storage.Client()
bucket = storage_client.bucket('my-bucket')

response = requests.get(
    f'https://github.com/googleapis/python-storage/tarball/9d5bb5622f17a0143fa6670406596e53d0068286',
    stream=True,
)

with tarfile.open(fileobj=response.raw, mode='r') as tf:
  for member in tf.getmembers():
    if not member.isfile():
      continue

    fileobj = tf.extractfile(member)
    bucket.blob(member.name).upload_from_file(fileobj)
```

#### Stack trace

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/main.py", line 70, in index
    tf.extractfile(m))
  File "/usr/local/lib/python3.9/tarfile.py", line 683, in read
    self.fileobj.seek(offset + (self.position - start))
  File "/usr/local/lib/python3.9/gzip.py", line 392, in seek
    return self._buffer.seek(offset, whence)
  File "/usr/local/lib/python3.9/_compression.py", line 137, in seek
    self._rewind()
  File "/usr/local/lib/python3.9/gzip.py", line 539, in _rewind
    super()._rewind()
  File "/usr/local/lib/python3.9/_compression.py", line 115, in _rewind
    self._fp.seek(0)
  File "/usr/local/lib/python3.9/gzip.py", line 110, in seek
    return self.file.seek(off)
io.UnsupportedOperation: seek
```

**Comment by jmdobry** [comment]
After further investigation I can provide example that works and an example that fails, the only difference is the tarfile being opened:

```
import tarfile

import requests

def print_member(member):
  print(f'name: {member.name}')
  print(f'size: {member.size}')
  print(f'mtime: {member.mtime}')
  print(f'mode: {member.mode}')
  print(f'type: {member.type}')
  print(f'linkname: {member.linkname}')
  print(f'uid: {member.uid}')
  print(f'gid: {member.gid}')
  print(f'uname: {member.uname}')
  print(f'gname: {member.gname}')
  print(f'pax_headers: {member.pax_headers}')
  print(f'isfile(): {member.isfile()}')
  print(f'isreg(): {member.isreg()}')
  print(f'isdir(): {member.isdir()}')
  print(f'issym(): {member.issym()}')
  print(f'islnk(): {member.islnk()}')
  print(f'ischr(): {member.ischr()}')
  print(f'isblk(): {member.isblk()}')
  print(f'isfifo(): {member.isfifo()}')
  print(f'isdev(): {member.isdev()}')

response = requests.get(f'https://github.com/googleapis/google-cloud-java/tarball/f39d323af5a0cad2c3c9bf6aa084d7356e89ca46', stream=True)

with tarfile.open(fileobj=response.raw, mode='r') as tf:
  for member in tf.getmembers():
    if not member.isfile():
      continue
    if member.name not in ('googleapis-google-cloud-java-f39d323/versions.txt', 'googleapis-python-storage-9d5bb56/.coveragerc'):
      continue
    print_member(member)

    fileobj = tf.extractfile(member.name)
    print(fileobj.read())
    print('\nIT WORKED!\n')

response = requests.get(f'https://github.com/googleapis/python-storage/tarball/9d5bb5622f17a0143fa6670406596e53d0068286', stream=True)

with tarfile.open(fileobj=response.raw, mode='r') as tf:
  for member in tf.getmembers():
    if not member.isfile():
      continue
    if member.name not in ('googleapis-google-cloud-java-f39d323/versions.txt', 'googleapis-python-storage-9d5bb56/.coveragerc'):
      continue
    print_member(member)

    fileobj = tf.extractfile(member.name)
    print(fileobj.read())
    print('\nIT FAILED!\n')
```

**Comment by jmdobry** [comment]
The solution was to wrap `response.raw` with `io.BytesIO(response.raw.read())` before passing it to `tarfile.open`, which necessitates reading the whole tarfile into memory. The problem here was that tarfile was attempting a "remote seek" on the HTTP response object, which wasn't support by either `requests` or GitHub's tarball endpoint.
