### ISSUE TITLE
Some download APIs are not working with service account credentials (google.api_core.exceptions.Forbidden: 403)

### ISSUE THREAD

**Issue by Iamcerba** [googleapis/python-storage#360]
#### Environment details

  - OS type and version: **Windows 10/Ubuntu**
  - Python version: **Python 3.7.8**
  - pip version: **pip 20.2.2**
  - `google-cloud-storage` version: **1.35.0**

#### Code example

```python
    import pathlib
    import json
    import tempfile

    from google.cloud import storage
    from google.cloud.storage import Blob, Bucket
    from google.oauth2 import service_account

    project_id = '...'
    # Service Account has "roles/storage.admin" role
    service_account_info_json_str = r'''{
      "type": "service_account",
      "project_id": "...",
      "private_key_id": "...",
      "private_key": "-----BEGIN PRIVATE KEY-----...-----END PRIVATE KEY-----\n",
      "client_email": "...",
      "client_id": "...",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "..."
    }
    '''
    bucket = 'test-bucket'
    path = 'test/test.json'

    storage_client = storage.Client(
        project=project_id,
        credentials=service_account.Credentials.from_service_account_info(
            json.loads(service_account_info_json_str)
        )
    )

    temp_dir = tempfile.gettempdir()
    temp_filename = temp_dir + '/blob.json'

    # Works
    target = pathlib.Path(temp_filename)

    with target.open(mode='wb') as downloaded_file:
        storage_client.download_blob_to_file(f'gs://{bucket}/{path}', downloaded_file)

    # Everything below doesn't.
    # Receiving google.api_core.exceptions.Forbidden: 403 GET ?alt=media: Request is prohibited by organization's policy.
    # vpcServiceControlsUniqueIdentifier: : ('Request failed with status code', 403, 'Expected one of', <HTTPStatus.OK: 200>, )
    blob: Blob = storage_client.bucket(bucket).blob(path)

    # Attempt 1
    text_result = blob.download_as_text()

    # Attempt 2
    blob.download_to_filename(temp_filename)

    # Attempt 3
    bytes_result: bytes = blob.download_as_bytes()
```

#### Stack trace
```
Traceback (most recent call last):
  File "...\venv\lib\site-packages\google\cloud\storage\client.py", line 724, in download_blob_to_file
    _raise_from_invalid_response(exc)
  File "...\venv\lib\site-packages\google\cloud\storage\blob.py", line 3886, in _raise_from_invalid_response
    raise exceptions.from_http_status(response.status_code, message, response=response)
google.api_core.exceptions.Forbidden: 403 GET https://storage.googleapis.com/download/storage/v1/b/....json?alt=media: Request is prohibited by organization&#39;s policy. vpcServiceControlsUniqueIdentifier: ...: ('Request failed with status code', 403, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>)
```

**Comment by Iamcerba** [comment]
Not actual, my mistake.
