### ISSUE TITLE
Force requests over IPv4 with python-storage-client

### ISSUE THREAD

**Issue by soichisumi** [googleapis/python-storage#604]
## Problem

Hi, I am trying to make a request to the [(Unofficial) GCS emulator](https://github.com/fsouza/fake-gcs-server) from a python script using docker-compose.
However, the request fails due to the error below. The docker-for-mac I am using does not seem to support IPv4, so I am trying to force IPv6 requests, but it does not seem to be working.
Is there any way to force IPv4 in python-storage-client?

## Desired behavior

Python-storage-client makes a request using IPv4 and the request succeeds.

## Example

docker-compose.yaml
```yaml
version: '3'
services:
  run:
    build: .
    container_name: run
    ports:
      - 9090:8080
    env_file: 
      - ./.env
    environment:
      - PORT=8080
  gcs:
    image: fsouza/fake-gcs-server:latest
    container_name: fake-gcs-server
    ports:
      - 4443:4443
    env_file: 
      - ./.env    
```

Python script

Python: 3.9.5
google-cloud-storage: "1.42.2"
requests: "2.26.0"

```python
from google.cloud import storage
from google.api_core.client_options import ClientOptions
from google.auth.credentials import AnonymousCredentials
from unittest.mock import patch
from multijob_sample import variables as vs
import requests
import urllib3
import urllib3.util.connection
import traceback

import socket
orig_getaddrinfo = socket.getaddrinfo
def getaddrinfoIPv4(host, port, family=0, type=0, proto=0, flags=0):
    print(f'running patched getaddrinfo')
    return orig_getaddrinfo(host=host, port=port, family=socket.AF_INET, type=type, proto=proto, flags=flags)
patcher = patch('socket.getaddrinfo', side_effect=getaddrinfoIPv4)
patcher.start()


# for fake-gcs-emulator
http_ssl_disabled = requests.Session()
http_ssl_disabled.verify = False
urllib3.disable_warnings(
       urllib3.exceptions.InsecureRequestWarning
)  # disable https warnings for https insecure certs

client = storage.Client(
    credentials=AnonymousCredentials(),
    project=vs.project_id,
    client_options=ClientOptions(api_endpoint='https://gcs:4443'), 
    _http=http_ssl_disabled,
)

def put_file(bucket_id: str, file, blobname: str):
    file.seek(0)
    try:
        client.get_bucket(bucket_id).blob(blob_name=blobname).upload_from_file(file)
        print(f'file {blobname} uploaded')
    except Exception as e:
        print(f'failed to put file: {blobname}')
        print(f'error: {e}')
        print(f'trace: {traceback.format_exc()}')

put_file("bucketid", file, "blobname") # do put_file
```

error
```txt
run              | running patched getaddrinfo
run              | failed to put file: test.csv
run              | error: HTTPSConnectionPool(host='::', port=4443): Max retries exceeded with url: /upload/resumable/efbbcde9c49cda2ff78e8da24371ea03 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8fb0765be0>: Failed to establish a new connection: [Errno -9] Address family for hostname not supported'))
run              | trace: Traceback (most recent call last):
run              |   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
run              |     conn = connection.create_connection(
run              |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
run              |     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
run              |   File "/usr/local/lib/python3.9/unittest/mock.py", line 1093, in __call__
run              |     return self._mock_call(*args, **kwargs)
run              |   File "/usr/local/lib/python3.9/unittest/mock.py", line 1097, in _mock_call
run              |     return self._execute_mock_call(*args, **kwargs)
run              |   File "/usr/local/lib/python3.9/unittest/mock.py", line 1158, in _execute_mock_call
run              |     result = effect(*args, **kwargs)
run              |   File "/app/multijob_sample/storage.py", line 26, in getaddrinfoIPv4
run              |     return orig_getaddrinfo(host=host, port=port, family=socket.AF_INET, type=type, proto=proto, flags=flags)
run              |   File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
run              |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
run              | socket.gaierror: [Errno -9] Address family for hostname not supported
```

**Comment by cojenco** [comment]
Thanks @soichisumi for the question. To clarify, docker for mac doesn't work on IPv6, so you are trying to use IPv4? 

The python-storage supports IPv4, so that should not be a problem. May I ask what does https://gcs:4443 resolve to? And have you tried setting `api_endpoint="https://0.0.0.0:4443"}`

**Comment by cojenco** [comment]
The decision of protocol is handled many degrees of dependency away from our client libraries themselves. The python-storage client utilizes the libraries requests and urllib3 under the hood. If I understand correctly, there is even no way to force IPv4 or IPv6 into the requests library. As noted [here](https://github.com/psf/requests/issues/1691), the protocol selection is not provided access to because the feature is handled way down in the standard library, not even exposed by httplib.

I see that you’ve patched out the part in socket that makes DNS requests. What happens if instead of using the python-storage client you just try to send an http request via requests? Would that work for you?

**Comment by soichisumi** [comment]
Hello,  @cojenco 
Thanks for your detailed and informative reply!

### dns resolution of `https://gcs:4443`

I have verified the name resolution from the container running the Python script to the gcs emulator.
it doesn't seem to have an IPv6 address.

```
root@be449982335d:/app# host gcs
gcs has address 172.18.0.2

root@be449982335d:/app# nslookup gcs
Server:         127.0.0.11
Address:        127.0.0.11#53

Non-authoritative answer:
Name:   gcs
Address: 172.18.0.2
```


### What happens if instead of using the python-storage client

It's taking a while, but I'll try.


### Other topic

I tried to implement put_file after `create_bucket` as shown below, and it succeeded in `create_bucket` and failed in `upload_from_file`.
Is there any logic in `FileUpload` that is related to this behavior?

script:
```
def create_bucket(bucket_id: str):
    try:
        client.get_bucket(bucket_id)
        return
    except Exception as e:
       print(f'bucket {bucket_id} is not found. creating...')
        print(f'error: {e}')
        print(f'trace: {traceback.format_exc()}')
    try:
        client.create_bucket(bucket_id)
        print(f'bucket {bucket_id} is created')
    except Exception as e:
        print(f'failed to create bucket. bucketid: {bucket_id}')
        print(f'error: {e}')
        print(f'trace: {traceback.format_exc()}')

def put_file(bucket_id: str, tempfile, blobname: str):
    tempfile.seek(0)
    try:
        client.get_bucket(bucket_id).blob(blob_name=blobname).upload_from_file(tempfile)
        print(f'file {blobname} uploaded')
    except Exception as e:
        print(f'failed to put file: {blobname}')
        print(f'error: {e}')
        print(f'trace: {traceback.format_exc()}')

with tempfile.TemporaryFile() as f:
        f.write('some content')
        create_bucket(bucket_id='bucket_id')
        put_file(
            bucket_id='bucket_id',
            tempfile=f,
            blobname="blobname"
        )
```

log:
```
run              | bucket is not found. creating...
run              | error: 404 GET https://gcs:4443/storage/v1/b/jmadata_20211004?projection=noAcl&prettyPrint=false: Not Found
run              | bucket jmadata_20211004 is created
run              | ----   getaddrinfoIPv4 patched   ---
run              | failed to put file: blobname
run              | error: HTTPSConnectionPool(host='::', port=4443): Max retries exceeded with url: /upload/resumable/5e68d0b5e4adde4da8a8d898a89db700 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4918907670>: Failed to establish a new connection: [Errno -9] Address family for hostname not supported'))
```

**Comment by adriangb** [comment]
I answered this question on [StackOverflow](https://stackoverflow.com/a/70417427/6582418), but copying here in case someone finds this first.

> This was, by far, one of the most annoying issues I've had to troubleshoot in a while. The solution is to run the emulator with the `-external-url http://<your docker compose service name>:<port>` option.
> 
> This issue occurs only with file uploads because it only happens for resumable uploads.
> For resumable uploads, the GCS client first "initiates" the resumable upload with the server, and in the response the server includes a URL for future requests to go to (not sure why, but it seems like a reasonable part of a complex API). The issue is that the emulator doesn't know it's own url! In fact, if you look at the logs for the emulator you'll see it prints out stuff like `server started at http://[::]:4443`. That `::` is the same `::` as you see in the error.
> So the emulator responds with it's `::` URL, and then a while later the client crashes trying to parse that URL.
> 
> I'm still not sure why running outside of docker-compose it works, I guess there's some special casing somewhere around "", "localhost" or "::"`.

So TLDR it's not a bug in this library, although this library _could_ do a better job of validating data / responses and/or giving a more user friendly error message.

I also filed https://github.com/fsouza/fake-gcs-server/issues/637 to see if they are able to make the situation more user-friendly.

**Comment by mjeverson** [comment]
> I answered this question on [StackOverflow](https://stackoverflow.com/a/70417427/6582418), but copying here in case someone finds this first.
> 
> > This was, by far, one of the most annoying issues I've had to troubleshoot in a while. The solution is to run the emulator with the `-external-url http://<your docker compose service name>:<port>` option.
> > This issue occurs only with file uploads because it only happens for resumable uploads.
> > For resumable uploads, the GCS client first "initiates" the resumable upload with the server, and in the response the server includes a URL for future requests to go to (not sure why, but it seems like a reasonable part of a complex API). The issue is that the emulator doesn't know it's own url! In fact, if you look at the logs for the emulator you'll see it prints out stuff like `server started at http://[::]:4443`. That `::` is the same `::` as you see in the error.
> > So the emulator responds with it's `::` URL, and then a while later the client crashes trying to parse that URL.
> > I'm still not sure why running outside of docker-compose it works, I guess there's some special casing somewhere around "", "localhost" or "::"`.
> 
> So TLDR it's not a bug in this library, although this library _could_ do a better job of validating data / responses and/or giving a more user friendly error message.
> 
> I also filed [fsouza/fake-gcs-server#637](https://github.com/fsouza/fake-gcs-server/issues/637) to see if they are able to make the situation more user-friendly.

Goodness gracious, thank you so much for this! I spent a whole morning tearing my hair out over this and your posts were SO helpful. Works for me!
