### ISSUE TITLE
Unable to stream read `.csv.gz` file via decompressive transcoding 

### ISSUE THREAD

**Issue by samiabboud** [googleapis/python-storage#607]
- OS type and version: Ubuntu 20.04 LTS
  - Python version: `python --version`: 3.8.10
  - pip version: `pip --version`: 20.0.2
  - `google-cloud-storage` version: `pip show google-cloud-storage`: 1.42.2

#### Code example

```python
import csv

bucket_name = "<bucket name goes here>"
blob_name = "<filename in bucket goes here>"

client = storage.Client()
bucket = client.bucket(bucket_name)
blob = bucket.blob(blob_name)

with blob.open("rt") as in_file:
    csv_reader = csv.DictReader(in_file)
    for row in csv_reader:
        yield row
````

#### Stack trace
```
for row in csv_reader:
  File "/usr/lib/python3.8/csv.py", line 111, in __next__
    row = next(self.reader)
  File "/.../venv/lib/python3.8/site-packages/google/cloud/storage/fileio.py", line 162, in read1
    return self.read(size)
  File "/.../venv/lib/python3.8/site-packages/google/cloud/storage/fileio.py", line 138, in read
    result += self._blob.download_as_bytes(
  File "/.../venv/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 1417, in download_as_bytes
    client.download_blob_to_file(
  File "/.../venv/lib/python3.8/site-packages/google/cloud/storage/client.py", line 1113, in download_blob_to_file
    blob_or_uri._do_download(
  File "/.../venv/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 1003, in _do_download
    response = download.consume(transport, timeout=timeout)
  File "/.../venv/lib/python3.8/site-packages/google/resumable_media/requests/download.py", line 171, in consume
    self._write_to_stream(result)
  File "/.../venv/lib/python3.8/site-packages/google/resumable_media/requests/download.py", line 105, in _write_to_stream
    for chunk in body_iter:
  File "/.../venv/lib/python3.8/site-packages/requests/models.py", line 758, in generate
    raise ContentDecodingError(e)
requests.exceptions.ContentDecodingError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))
```

I traced the issue back to having `Client.download_blob_to_file` set `headers["accept-encoding"] = "gzip"` which prevents decompressive transcoding.

Thank you for the help, and please let me know if I'm getting it wrong.

**Comment by cojenco** [comment]
Thanks samiabboud for your report! We're now investigating this issue. I may be back to request more info if needed.

**Comment by cojenco** [comment]
Update: I am unable to reproduce your issue. Using your code example, I tried reading two large CSV files and both worked for me without any errors. I'll continue to investigate the `blob.download_as_bytes()` method. 

Meanwhile, could you check to see if you run into the same issue reading different source csv files? Thanks!

**Comment by samiabboud** [comment]
Thank you for investigating @cojenco .

Here's a self contained snippet to reproduce (just edit the bucket name)

```python
import gzip
import random

from google.cloud import storage

BUCKET_NAME = <YOUR BUCKET NAME HERE>

LINES = 500

new_file = "/tmp/test_file.csv.gz"

with gzip.open(new_file, "wt", newline="") as f:
    csv_writer = csv.DictWriter(f, fieldnames=["A", "B"])
    csv_writer.writeheader()
    for _  in range(LINES):
        csv_writer.writerow({
            "A": random.randint(0, 100),
            "B": random.randint(0, 100)
        })

client = storage.Client()
bucket = client.bucket(BUCKET_NAME)

blob_name = "test/test_file.csv.gz"
blob = bucket.blob(blob_name)
blob.upload_from_filename(new_file)

blob.content_encoding = "gzip"
blob.patch()

output = blob.download_as_bytes(client, start=0, end=100)
print(output)
output = blob.download_as_bytes(client, start=100, end=200)
```

and here's my pip freeze output, just in case:

```
aiohttp==3.7.4.post0
async-timeout==3.0.1
attrs==21.2.0
bokeh==2.3.3
cachetools==4.2.2
certifi==2021.5.30
cffi==1.14.5
chardet==4.0.0
click==7.1.2
cryptography==3.4.7
decorator==5.1.0
ecdsa==0.17.0
fastapi==0.62.0
fsspec==2021.9.0
gcsfs==2021.9.0
google-api-core==1.30.0
google-auth==1.32.1
google-auth-oauthlib==0.4.6
google-cloud-bigquery==2.11.0
google-cloud-core==1.7.1
google-cloud-secret-manager==2.1.0
google-cloud-storage==1.42.3
google-crc32c==1.1.2
google-resumable-media==1.3.1
googleapis-common-protos==1.53.0
grpc-google-iam-v1==0.12.3
grpcio==1.38.1
gunicorn==20.0.4
h11==0.12.0
httptools==0.1.1
idna==2.10
iniconfig==1.1.1
Jinja2==3.0.1
libcst==0.3.19
MarkupSafe==2.0.1
multidict==5.1.0
mypy-extensions==0.4.3
networkx==2.6.3
numpy==1.21.2
oauthlib==3.1.1
packaging==21.0
pandas==1.1.5
Pillow==8.3.2
pluggy==0.13.1
proto-plus==1.19.0
protobuf==3.17.3
psycopg2==2.8.6
py==1.10.0
pyarrow==5.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pydantic==1.7.4
pyparsing==2.4.7
pytest==6.2.2
python-dateutil==2.8.2
python-dotenv==0.15.0
python-jose==3.3.0
python-json-logger==2.0.1
pytz==2021.1
PyYAML==5.4.1
requests==2.25.1
requests-oauthlib==1.3.0
rsa==4.7.2
scipy==1.7.1
sentry-sdk==1.4.2
six==1.16.0
SQLAlchemy==1.3.24
starlette==0.13.8
toml==0.10.2
tornado==6.1
typing-extensions==3.10.0.0
typing-inspect==0.7.1
urllib3==1.26.6
uvicorn==0.13.2
uvloop==0.14.0
yarl==1.6.3
```

Happy to provide more info, or test, if useful.

**Comment by cojenco** [comment]
Thanks for your patience @samiabboud! We've checked with the team and GCS does not support range headers with decompressive transcoding, as stated in our [docs](https://cloud.google.com/storage/docs/transcoding#range). 

May we get more information on what your program is trying to do so we can further assist? Is it more important to do decompressive transcoding or byte range downloads?

**Comment by cozos** [comment]
@andrewsg This also breaks `download_as_string()`

**Comment by andrewsg** [comment]
@cozos Can you be more specific? What exactly breaks and in what way?

**Comment by cozos** [comment]
If you try to call `download_as_string()` on a blob with `gzip` transcoding, it will break.

Calling it on the first "chunk" works:
```
>>> print(blob.download_as_string(start=0, end=100))
b'[{"avro_versio'
```

On the second chunk it breaks:
```
```
>>> print(blob.download_as_string(start=100, end=200))
Traceback (most recent call last):
  File "/home/arwin.tio/projects/cruise/.venv/cruise_py3/lib/python3.9/site-packages/urllib3/response.py", line 407, in _decode
    data = self._decoder.decompress(data)
  File "/home/arwin.tio/projects/cruise/.venv/cruise_py3/lib/python3.9/site-packages/google/resumable_media/requests/download.py", line 501, in decompress
    return super(_GzipDecoder, self).decompress(data)
  File "/home/arwin.tio/projects/cruise/.venv/cruise_py3/lib/python3.9/site-packages/urllib3/response.py", line 94, in decompress
    ret += self._obj.decompress(data)
zlib.error: Error -3 while decompressing data: incorrect header check
```

Note that if you download the whole string without specifying any chunking, it still breaks. Presumably this is because it does chunking under the hood.
```
>>> blob.download_as_string()
Traceback (most recent call last):
  File "/home/arwin.tio/projects/cruise/.venv/cruise_py3/lib/python3.9/site-packages/urllib3/response.py", line 407, in _decode
    data = self._decoder.decompress(data)
  File "/home/arwin.tio/projects/cruise/.venv/cruise_py3/lib/python3.9/site-packages/google/resumable_media/requests/download.py", line 501, in decompress
    return super(_GzipDecoder, self).decompress(data)
  File "/home/arwin.tio/projects/cruise/.venv/cruise_py3/lib/python3.9/site-packages/urllib3/response.py", line 94, in decompress
    ret += self._obj.decompress(data)
zlib.error: Error -3 while decompressing data: incorrect data check
```

This is on `Python 3.9.15` and `google-cloud-storage==2.1.0`

IMO, if you try to call `blob.download_as_string()` on a gzip transcoded blob, it should be smart enough to do your `Option 1` workaround of downloading to a local file. Otherwise gzip trancoded blobs are pretty much not supported with Python GCS library.
