### ISSUE TITLE
ValueError: Bytes stream is in unexpected state when writing to blob in chunks

### ISSUE THREAD

**Issue by samiabboud** [googleapis/python-storage#611]
OS type and version: Ubuntu 20.04 LTS
Python version: python --version: 3.8.10
pip version: pip --version: 20.0.2
google-cloud-storage version: pip show google-cloud-storage: 1.42.2

#### Steps to reproduce

  1. Run code (update bucket name)

#### Code example

```python

import csv
import random

from google.cloud import storage

BUCKET_NAME = <YOUR BUCKET NAME HERE>

LINES = 50000000

new_blob_filename = "test/test_file.csv"

client = storage.Client()
bucket = client.bucket(BUCKET_NAME)
blob = bucket.blob(new_blob_filename)

with blob.open("wt", chunk_size=262144*300, newline="") as f:
    csv_writer = csv.DictWriter(f, fieldnames=["A", "B", "C", "D", "E"])
    csv_writer.writeheader()
    for _ in range(LINES):
        csv_writer.writerow({
            "A": random.randint(0, 100),
            "B": random.randint(0, 100),
            "C": random.randint(0, 100),
            "D": random.randint(0, 100),
            "E": random.randint(0, 100)
        })
```

#### Stack trace
```
Traceback (most recent call last):
  File ".../clean_venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File ".../clean_venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File ".../clean_venv/lib/python3.8/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1046, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.8/http/client.py", line 968, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.8/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
socket.timeout: The write operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../clean_venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File ".../clean_venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File ".../clean_venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File ".../clean_venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File ".../clean_venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File ".../clean_venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File ".../clean_venv/lib/python3.8/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1046, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.8/http/client.py", line 968, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.8/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "reproduce.py", line 50, in <module>
    csv_writer.writerow({
  File "/usr/lib/python3.8/csv.py", line 154, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File ".../clean_venv/lib/python3.8/site-packages/google/cloud/storage/fileio.py", line 334, in write
    self._upload_chunks_from_buffer(num_chunks)
  File ".../clean_venv/lib/python3.8/site-packages/google/cloud/storage/fileio.py", line 388, in _upload_chunks_from_buffer
    upload.transmit_next_chunk(transport)
  File ".../clean_venv/lib/python3.8/site-packages/google/resumable_media/requests/upload.py", line 516, in transmit_next_chunk
    return _helpers.wait_and_retry(
  File ".../clean_venv/lib/python3.8/site-packages/google/resumable_media/_helpers.py", line 205, in wait_and_retry
    raise error
  File ".../clean_venv/lib/python3.8/site-packages/google/resumable_media/_helpers.py", line 182, in wait_and_retry
    response = func()
  File ".../clean_venv/lib/python3.8/site-packages/google/resumable_media/requests/upload.py", line 508, in retriable_request
    result = transport.request(
  File ".../clean_venv/lib/python3.8/site-packages/google/auth/transport/requests.py", line 475, in request
    response = super(AuthorizedSession, self).request(
  File ".../clean_venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File ".../clean_venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File ".../clean_venv/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', timeout('The write operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "reproduce.py", line 50, in <module>
    csv_writer.writerow({
  File ".../clean_venv/lib/python3.8/site-packages/google/cloud/storage/fileio.py", line 408, in close
    self._upload_chunks_from_buffer(1)
  File ".../clean_venv/lib/python3.8/site-packages/google/cloud/storage/fileio.py", line 388, in _upload_chunks_from_buffer
    upload.transmit_next_chunk(transport)
  File ".../clean_venv/lib/python3.8/site-packages/google/resumable_media/requests/upload.py", line 504, in transmit_next_chunk
    method, url, payload, headers = self._prepare_request()
  File ".../clean_venv/lib/python3.8/site-packages/google/resumable_media/_upload.py", line 609, in _prepare_request
    raise ValueError(msg)
ValueError: Bytes stream is in unexpected state. The local stream has had 235929600 bytes read from it while 157286400 bytes have already been updated (they should match).
```

It seems like that writing does not recover when a chunk times out. My workaround was to set `chunk_size` to `262144*10`. The larger the chunk size the higher the probability to reproduce I believe.

**Comment by cojenco** [comment]
In addition to writing in smaller chunks, you can also customize retries and include the precondition query param `if_generation_match`. With retries configured, the upload operation will retry in cases of connection errors and other retryable errors (such as a 503). 

As shown below, you can try customizing the total timeout deadline to 600 seconds instead of the default 120 seconds, and you can shorten the wait time by customizing the multiplier. See [here](https://googleapis.dev/python/storage/latest/retry_timeout.html) for more info on configuring retries.

```
from google.cloud.storage.retry import DEFAULT_RETRY_IF_GENERATION_SPECIFIED

# extend the total deadline to 600 seconds and set multiplier to 1.2
modified_retry = DEFAULT_RETRY_IF_GENERATION_SPECIFIED.retry_policy.with_deadline(600)
modified_retry = modified_retry.with_delay(multiplier=1.2)
print(modified_retry.__str__())

# setting if_generation_match=0 if you are writing a new blob, else if_generation_match=blob.generation
with blob.open("wt", chunk_size=262144*100, newline="", if_generation_match=0, retry=modified_retry) as f:
    csv_writer = csv.DictWriter(f, fieldnames=["A", "B", "C", "D", "E"])
    csv_writer.writeheader()
    for _ in range(LINES):
        csv_writer.writerow({
            "A": random.randint(0, 100),
            "B": random.randint(0, 100),
            "C": random.randint(0, 100),
            "D": random.randint(0, 100),
            "E": random.randint(0, 100)
        })
```
