### ISSUE TITLE
Cannot stream-write a zipfile

### ISSUE THREAD

**Issue by Clockwork-Muse** [googleapis/python-storage#631]
I'm attempting to stream-write an uncompressed zip file (200MB+ -> 1GB+ eventually, mostly ~3MB images) to avoid writing to disk.  Unfortunately when the zip file is closed it attempts to at least partially flush the stream, and the storage client seems to assume that a flush will only occur to close the streamed file, which isn't the case here (and seems wrong in the general sense, since buffers are often flushed when they reach saturation).

#### Environment details

  - OS type and version: Ubuntu 20.04 (custom devcontainer docker image)
  - Python version: 3.8.10
  - pip version: 21.3
  - `google-cloud-storage` version: 1.42.3

#### Code example

```python
import zipfile

from google.cloud.storage import Blob, Client

client = Client("some-account")
blob = Blob.from_string("gs://some-bucket/some-folder/something.zip", client)

with blob.open(mode="wb") as blob_file, \
    zipfile.ZipFile(blob_file, mode="w") as zip_file:
    # Empty/not empty doesn't matter, the same error is generated
    pass
```

#### Stack trace
```
Traceback (most recent call last):
  File "s.py", line 14, in <module>
    pass
  File "/usr/lib/python3.8/zipfile.py", line 1312, in __exit__
    self.close()
  File "/usr/lib/python3.8/zipfile.py", line 1839, in close
    self._write_end_record()
  File "/usr/lib/python3.8/zipfile.py", line 1947, in _write_end_record
    self.fp.flush()
  File "/workspaces/someproject/.pyenv/lib/python3.8/site-packages/google/cloud/storage/fileio.py", line 401, in flush
    raise io.UnsupportedOperation(
io.UnsupportedOperation: Cannot flush without finalizing upload. Use close() instead.
```

</ br>

#### Workaround
Insert an `io.BufferedWriter`:

```python
import io
import zipfile

from google.cloud.storage import Blob, Client

client = Client("some-account")
blob = Blob.from_string("gs://some-bucket/some-folder/something.zip", client)

with blob.open(mode="wb") as blob_file, \
    io.BufferedWriter(blob_file) as binary_file, \
    zipfile.ZipFile(binary_file, mode="w") as zip_file:
    # Empty/not empty doesn't matter, the same error is generated
    pass
```

This results in the file being written to cloud storage (and at least for a simple case, including correctly written contents), but it prints a new error:
```
Traceback (most recent call last):
  File "s.py", line 24, in <module>
    pass
  File "/workspaces/someproject/.pyenv/lib/python3.8/site-packages/google/cloud/storage/fileio.py", line 406, in close
    self._checkClosed()  # Raises ValueError if closed.
  File "/workspaces/someproject/.pyenv/lib/python3.8/site-packages/google/cloud/storage/fileio.py", line 413, in _checkClosed
    raise ValueError("I/O operation on closed file.")
ValueError: I/O operation on closed file.
```

**Comment by Clockwork-Muse** [comment]
For files of any real size, the current workaround I give is not sufficient - I get errors around the ~50MB range:
```
Traceback (most recent call last):
  File "src/s.py", line 27, in <module>
    o.export_function(**{f"some_image_{i}.png": img, f"some{i}.jpg": img})
  File "/some_project/src/output_manager.py", line 76, in export_function
    image_file.write(image_bytes)
  File "/usr/lib/python3.8/zipfile.py", line 1141, in write
    self._fileobj.write(data)
OSError: raw write() returned invalid length 41943095 (should have been between 0 and 55)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/contextlib.py", line 510, in __exit__
    if cb(*exc_details):
  File "/usr/lib/python3.8/zipfile.py", line 1312, in __exit__
    self.close()
  File "/usr/lib/python3.8/zipfile.py", line 1839, in close
    self._write_end_record()
  File "/usr/lib/python3.8/zipfile.py", line 1947, in _write_end_record
    self.fp.flush()
OSError: raw write() returned invalid length 41943601 (should have been between 0 and 561)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/contextlib.py", line 510, in __exit__
    if cb(*exc_details):
OSError: raw write() returned invalid length 41943601 (should have been between 0 and 561)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/s.py", line 28, in <module>
    o.export_text_function(gt, [])
  File "/some_project/src/output_manager.py", line 200, in __exit__
    return self.__context_stack.__exit__(exc_type, exc_val, exc_tb)
  File "/usr/lib/python3.8/contextlib.py", line 525, in __exit__
    raise exc_details[1]
  File "/usr/lib/python3.8/contextlib.py", line 510, in __exit__
    if cb(*exc_details):
  File "/some_project/.pyenv/lib/python3.8/site-packages/google/cloud/storage/fileio.py", line 406, in close
    self._checkClosed()  # Raises ValueError if closed.
  File "/some_project/.pyenv/lib/python3.8/site-packages/google/cloud/storage/fileio.py", line 413, in _checkClosed
    raise ValueError("I/O operation on closed file.")
ValueError: I/O operation on closed file.
```

... it's not clear to me why `export_text_function` is getting called here, since it's the `export_function` call that's throwing the error, and exiting the wrapping context that I have (strategically placed `print`-debugging lines aren't being called, so I'm really confused).

In any case, the archived files up to that point have been written to the gcloud storage location, and it can be downloaded and unpacked, and those files read.

**Comment by andrewsg** [comment]
Okay. I'll work on a new behavior here. In the meantime, this is perhaps a silly workaround, but inside your `with` statement you can set the private attribute `blob_file._text_mode = True` to silence the `flush()` error. This won't actually put the blob into text mode, as long as you set the private attribute directly instead of through the constructor.
