### ISSUE TITLE
Retry did not occur

### ISSUE THREAD

**Issue by nitishxp** [googleapis/python-storage#718]
Hi I am using python39 Cloud function runtime

Lib that i am using is
google-cloud-bigquery==2.28.1
google-auth==1.30.0
google-cloud-pubsub==2.2.0
google-cloud-scheduler==2.1.0
google-cloud-storage==1.38.0
google-cloud-kms==2.2.0
google-cloud-secret-manager==2.1.0
google-api-python-client==2.30.0

`
Expecting value: line 1 column 1 (char 0) Traceback (most recent call last): File "/workspace/functions.py", line 50, in wrapper response = wrapped_func(*args, **kwargs) File "/workspace/main.py", line 167, in function1 gcs.get_bucket(bucket_name) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/storage/client.py", line 402, in get_bucket bucket.reload( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/storage/bucket.py", line 1001, in reload super(Bucket, self).reload( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/storage/_helpers.py", line 218, in reload api_response = client._connection.api_request( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/storage/_http.py", line 78, in api_request return call() File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func return retry_target( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/api_core/retry.py", line 189, in retry_target return target() File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/_http.py", line 473, in api_request response = self._make_request( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/_http.py", line 337, in _make_request return self._do_request( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/_http.py", line 375, in _do_request return self.http.request( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/auth/transport/requests.py", line 478, in request self.credentials.before_request(auth_request, method, url, request_headers) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/auth/credentials.py", line 133, in before_request self.refresh(request) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/oauth2/service_account.py", line 376, in refresh access_token, expiry, _ = _client.jwt_grant( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/oauth2/_client.py", line 193, in jwt_grant response_data = _token_endpoint_request(request, token_uri, body) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/oauth2/_client.py", line 161, in _token_endpoint_request response_status_ok, response_data = _token_endpoint_request_no_throw( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/oauth2/_client.py", line 121, in _token_endpoint_request_no_throw response_data = json.loads(response_body) File "/opt/python3.9/lib/python3.9/json/__init__.py", line 346, in loads return _default_decoder.decode(s) File "/opt/python3.9/lib/python3.9/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/opt/python3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)	`

**Comment by Breathtender** [comment]
Hi @nitishxp, thanks for your report. I'm having a little bit of a hard time understanding your report, could you share a little bit more information?
What would be most helpful is if you could share what you were trying to do and what was the expected behavior, that caused this. Ideally share a code snippet where this error happened so we can try to reproduce it.

Lastly, if you could try upgrading to the latest google-cloud-storage version (2.1.0) first to see if that fixes anything and let us know, that would be most helpful.

Thanks again!

**Comment by danielduhh** [comment]
Closing due to inactivity. Will be happy to open back up if upgrading your client doesn't fix this or if you're able to add more information @nitishxp!
