### ISSUE TITLE
blob.download_as_bytes fails when called with client.batch()

### ISSUE THREAD

**Issue by jignesh-crest** [googleapis/python-storage#948]
#### Environment details

  - OS type and version: Ubuntu
  - Python version: `3.10`
  - pip version: `21.2.4`
  - `google-cloud-storage` version: `2.7.0`

#### Code example

```python
blob_list= storage_client.list_blobs(bucket_or_name="bucket-name")

    data_dict = {}
    with storage_client.batch():
        for blob in blob_list:
            data_dict[blob.name] = blob.download_as_bytes()

    print(data_dict)
```

#### Stack trace
```
Traceback (most recent call last):
  File "/root/connectorDevelopment/GCP/batch/manual-get-blob.py", line 45, in <module>
    print_blob_acl(
  File "/root/connectorDevelopment/GCP/batch/manual-get-blob.py", line 34, in print_blob_acl
    with storage_client.batch():
  File "/root/connectorDevelopment/GCP/batch/lib/python3.10/site-packages/google/cloud/storage/batch.py", line 286, in __exit__
    self.finish()
  File "/root/connectorDevelopment/GCP/batch/lib/python3.10/site-packages/google/cloud/storage/batch.py", line 256, in finish
    headers, body, timeout = self._prepare_batch_request()
  File "/root/connectorDevelopment/GCP/batch/lib/python3.10/site-packages/google/cloud/storage/batch.py", line 202, in _prepare_batch_request
    raise ValueError("No deferred requests")
ValueError: No deferred requests
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Do let me know if I've missed any detail.
Thanks!

**Comment by cojenco** [comment]
Hi @jignesh-crest, thank you for your question. Cloud Storage does not support batch operations for downloading or uploading. Please refer to the [official documentation](https://cloud.google.com/storage/docs/batch) for more details.

**Comment by andrewsg** [comment]
The new `transfer_manager.py` feature preview might be able to help with this workflow. https://github.com/googleapis/python-storage/pull/943
