### ISSUE TITLE
`The billing account for the owning project is disabled in state closed` when using the wrong credential type

### ISSUE THREAD

**Issue by multimeric** [googleapis/python-storage#951]
#### Environment details

  - OS type and version: macOS Monterey
  - Python version: 3.9.12
  - pip version: 22.3.1
  - `google-cloud-storage` version: 2.7.0

#### Steps to reproduce

One instance where this happens is if you use an authenticated client for public data.

1. Authenticate using `gcloud auth application-default login`
2. ```python
    from google.cloud import storage
    client = storage.Client()
    storage.Blob.from_string("gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.fai", client=client).download_as_text()
    ```
  3. This should then fail with `The billing account for the owning project is disabled in state closed: ('Request failed with status code', 403, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>)`

#### Stack trace
```
Traceback (most recent call last):
  File "/Users/milton.m/Library/Caches/pypoetry/virtualenvs/amppdmemory-9Dgecajf-py3.9/lib/python3.9/site-packages/google/cloud/storage/client.py", line 1086, in download_blob_to_file
    blob_or_uri._do_download(
  File "/Users/milton.m/Library/Caches/pypoetry/virtualenvs/amppdmemory-9Dgecajf-py3.9/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 984, in _do_download
    response = download.consume(transport, timeout=timeout)
  File "/Users/milton.m/Library/Caches/pypoetry/virtualenvs/amppdmemory-9Dgecajf-py3.9/lib/python3.9/site-packages/google/resumable_media/requests/download.py", line 232, in consume
    return _request_helpers.wait_and_retry(
  File "/Users/milton.m/Library/Caches/pypoetry/virtualenvs/amppdmemory-9Dgecajf-py3.9/lib/python3.9/site-packages/google/resumable_media/requests/_request_helpers.py", line 148, in wait_and_retry
    response = func()
  File "/Users/milton.m/Library/Caches/pypoetry/virtualenvs/amppdmemory-9Dgecajf-py3.9/lib/python3.9/site-packages/google/resumable_media/requests/download.py", line 214, in retriable_request
    self._process_response(result)
  File "/Users/milton.m/Library/Caches/pypoetry/virtualenvs/amppdmemory-9Dgecajf-py3.9/lib/python3.9/site-packages/google/resumable_media/_download.py", line 188, in _process_response
    _helpers.require_status_code(
  File "/Users/milton.m/Library/Caches/pypoetry/virtualenvs/amppdmemory-9Dgecajf-py3.9/lib/python3.9/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 403, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/milton.m/Library/Caches/pypoetry/virtualenvs/amppdmemory-9Dgecajf-py3.9/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 1612, in download_as_text
    data = self.download_as_bytes(
  File "/Users/milton.m/Library/Caches/pypoetry/virtualenvs/amppdmemory-9Dgecajf-py3.9/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 1387, in download_as_bytes
    client.download_blob_to_file(
  File "/Users/milton.m/Library/Caches/pypoetry/virtualenvs/amppdmemory-9Dgecajf-py3.9/lib/python3.9/site-packages/google/cloud/storage/client.py", line 1099, in download_blob_to_file
    _raise_from_invalid_response(exc)
  File "/Users/milton.m/Library/Caches/pypoetry/virtualenvs/amppdmemory-9Dgecajf-py3.9/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 4368, in _raise_from_invalid_response
    raise exceptions.from_http_status(response.status_code, message, response=response)
google.api_core.exceptions.Forbidden: 403 GET https://storage.googleapis.com/download/storage/v1/b/gcp-public-data--broad-references/o/hg38%2Fv0%2FHomo_sapiens_assembly38.fasta.fai?alt=media: The billing account for the owning project is disabled in state closed: ('Request failed with status code', 403, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>)
```

## Discussion

Firstly I think this error is quite confusing. It has nothing to do with the billing account, and in fact relates to the fact that the wrong set of credentials were used. Of course this can be trivially solved by using `client = storage.Client.create_anonymous_client()`, but this isn't obvious at all.

Secondly, this error also occurs when working with a bucket that you do have read access to, but whose project you don't belong to. In this case, I'm not sure what the correct solution is, and I would like to know what mechanism can be used in `google.cloud.storage` to handle this use case.

**Comment by cojenco** [comment]
Hi multimeric@ thanks for the question. We encourage users to use `AnonymousCredentials` when accessing public data, as noted in our [documentation and samples](https://cloud.google.com/storage/docs/access-public-data#client-libraries). As you can see in the docs, depending on how you want to access public data, authentication may be required or not. In the python client, authentication is not required. 

If your project has a billing account in good standing, you should not run into the mentioned error either. I followed your repro steps to run your code snippet locally, and was able to fetch public data with no issues. 

As for working with a bucket that you have read access under a closed state billing account, I'm checking with our internal teams if that is feasible.

Could you check to see if the issue persists if you use a project with a valid billing account?

**Comment by cojenco** [comment]
Closing due to inactivity. Will be happy to open back up if you have further questions.
